export const productsMock = {
  results: 2,
  paginationResult: {
    currentPage: 1,
    limit: 10,
    numberOfPages: 1,
  },
  data: {
    products: [
      {
        _id: "641351649",
        title: "سخان مياه كهربائي تورنيدو 50 لتر",
        price: "3500",
        images: [
          "https://m.media-amazon.com/images/I/51B00AJdN4L._AC_SX466_.jpg",
          "https://m.media-amazon.com/images/I/51B00AJdN4L._AC_SY450_.jpg",
        ],
        averageRating: 4.5,
        quantity: 10,
        description: "سخان مياه كهربائي عالي الجودة بسعة 50 لتر، مزود بنظام حماية متطور.",
        Category: "سخانات",
        brand: "Tornado",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        __v: "0",
      },
      {
        _id: "641351650",
        title: "سخان مياه غاز أوليمبيك 10 لتر",
        price: "4200",
        images: [
          "https://m.media-amazon.com/images/I/51GPNcxvXSL._AC_SY450_.jpg",
          "https://m.media-amazon.com/images/I/51GPNcxvXSL._AC_SY450_.jpg",
        ],
        averageRating: 4.0,
        quantity: 5,
        description: "سخان مياه غاز ديجيتال سعة 10 لتر بتصميم عصري وأمان كامل.",
        Category: "سخانات",
        brand: "Olympic Electric",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        __v: "0",
      },
      {
        _id: "641351651",
        title: "سخان مياه كهربائي فريش 30 لتر",
        price: "2800",
        images: [
          "https://m.media-amazon.com/images/I/51B00AJdN4L._AC_SX466_.jpg",
        ],
        averageRating: 4.8,
        quantity: 15,
        description: "سخان مياه كهربائي فريش بسعة 30 لتر مع عزل حراري قوي لتوفير الكهرباء.",
        Category: "سخانات",
        brand: "Fresh",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        __v: "0",
      },
      {
        _id: "641351652",
        title: "سخان مياه كهربائي أريستون 80 لتر",
        price: "5500",
        images: [
          "https://m.media-amazon.com/images/I/51GPNcxvXSL._AC_SY450_.jpg",
        ],
        averageRating: 4.2,
        quantity: 2,
        description: "سخان مياه كهربائي أريستون إيطالي بسعة 80 لتر، مثالي للعائلات الكبيرة.",
        Category: "سخانات",
        brand: "Ariston",
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        __v: "0",
      },
    ],
  },
};
