"use client";
// import type { Metadata } from "next";
import {Tajawal} from "next/font/google";
import "./globals.css";
import {store} from "../redux/store";
import { Provider } from "react-redux";
import {  ToastContainer} from 'react-toastify';
import NetworkStatus from "@/Components/NetworkStatus";
import { SessionProvider } from "next-auth/react";
import { SpeedInsights } from "@vercel/speed-insights/next"

const tajawal = Tajawal({
  subsets: ["arabic", "latin"],
  variable: "--font-tajawal",
  weight: ["400", "700"],
});




// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
//   icons: {
//     icon: '/favicon.ico', // المسار إلى ملف الأيقونة
//   }
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        
      <body
        className={`  ${tajawal.variable } font-tajawal `}
      >
        <SpeedInsights/>
         <SessionProvider>
        <NetworkStatus/>
        <Provider store={store}>
        {children}
        </Provider>
        <ToastContainer />
        </SessionProvider>
      </body>
    </html>
  );
}
